name: deploy COD4 to ghcr.io
on:
  push:
    paths:
      - cod4/bin/*
      - cod4/Dockerfile
  workflow_dispatch:
jobs:
  docker-cod4:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: './cod4'
    steps:
      - name: 'Checkout Source Code'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build and Deploy Docker Container'
        run: |
          docker build . --tag ghcr.io/derkalle4/docker-pelican-cod4:latest
          docker push ghcr.io/derkalle4/docker-pelican-cod4:latest
