name: deploy BFBC2 to ghcr.io
env:
  DOTNET_VERSION: '6.0.x'
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-bfbc2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './bfbc2'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/derkalle4/docker-pelican-bfbc2:latest
          docker push ghcr.io/derkalle4/docker-pelican-bfbc2:latest
